import { brandName } from "@/constants/common";
import { userFlowAtom } from "@/states/atom";
import Head from "next/head";
import { useRouter } from "next/navigation";
import { useRecoilState } from "recoil";

export default function Login() {

  const { push } = useRouter();

  const [userFlow, setUserFlow] = useRecoilState(userFlowAtom);

  return (
    <>
       <Head>
        <title>{brandName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{
        background: `url(/splash-screen.png) no-repeat`,
        backgroundSize: '100% 100%',
        position: 'fixed',
        bottom: '0px',
        top: '0px',
        right: '0px',
        left: '0px',
        padding: '46px',
      }}>
        <div style={{bottom: '320px', left: '120px', position: 'absolute'}} className="d-flex align-items-center w-25 justify-content-between">
          <div 
            style={{padding: '10px 20px 10px 20px', border: 'solid', borderColor: 'white', borderWidth: '2px', color: 'black', fontWeight: 'bold', cursor: 'grab'}}
            className="rounded"
            onClick={() => {
              setUserFlow("host");
              push('/login');
            }}
          >
            List your Space
          </div>
          <div
            style={{padding: '10px 20px 10px 20px', border: 'solid', borderColor: 'white', borderWidth: '2px', color: 'black', fontWeight: 'bold', cursor: 'grab'}}
            className="rounded"
            onClick={() => {
              setUserFlow("user");
              push('/login');
            }}
          >
            Post in a Space
          </div>
        </div>
      </div>
    </>
  );
}